/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
/*                                                      */
/* File:  fuzzyControl.h                                */
/*                                                      */
/* Author: Automatically generated by Xfuzzy            */
/*                                                      */
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

#ifndef XFUZZY
#define XFUZZY
/*------------------------------------------------------*/
/* Fuzzy Number                                         */
/*------------------------------------------------------*/

 typedef struct {
   double (* equal)(double x);
   double (* center)();
   double (* basis)();
   double (* param)(int i);
 } Consequent;

 typedef struct {
   double min;
   double max;
   double step;
   double (* imp)(double a, double b);
   double (* also)(double a, double b);
   int length;
   double* degree;
   int inputlength;
   double* input;
   Consequent* conc;
 } FuzzyNumber;

#endif /* XFUZZY */


#ifndef XFUZZY_fuzzyControl
#define XFUZZY_fuzzyControl
/*------------------------------------------------------*/
/* Inference Engine                                     */
/*------------------------------------------------------*/

void fuzzyControlInferenceEngine(double Ecenit, double D_Ecenit, double Eazimut, double D_Eazimut, double* PWM_cenit, double* PWM_azimut);

#endif /* XFUZZY_fuzzyControl */
