/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
/*                                                      */
/* File:  fuzzyControl.c                                */
/*                                                      */
/* Author: Automatically generated by Xfuzzy            */
/*                                                      */
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

#include <stdio.h>
#include <math.h>
#include "fuzzyControl.h"

/*======================================================*/
/*  MembershipFunction FMF_xfl_sh_triangular            */
/*======================================================*/

/*------------------------------------------------------*/
/* Function to compute an equal relationship            */
/*------------------------------------------------------*/

static double FMF_xfl_sh_triangular_equal(double x, int i, double min, double max, double step, double *p, int length) {
      if(i==0 && x<p[0]) return 1;
      if(i==length-1 && x>p[length-1]) return 1;
      double a = (i==0? min : p[i-1]);
      double b = p[i];
      double c = (i==length-1? max : p[i+1]);
      return (a<x && x<=b? (x-a)/(b-a) : (b<x && x<c? (c-x)/(c-b) : 0));
}

/*======================================================*/
/*  MembershipFunction MF_xfl_singleton                 */
/*======================================================*/

/*------------------------------------------------------*/
/* Function to compute an equal relationship            */
/*------------------------------------------------------*/

static double MF_xfl_singleton_equal(double x, double min, double max, double step, double a) {
    return (x==a? 1 : 0); 

}

/*======================================================*/
/*  Operatorset OP_operadores                           */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the operator AND                      */
/*------------------------------------------------------*/

static double OP_operadores_And(double a, double b) {
    return (a<b? a : b); 

}

/*------------------------------------------------------*/
/* Description of the defuzzification method            */
/*------------------------------------------------------*/

static double OP_operadores_Defuz(FuzzyNumber mf) {
 double min = mf.min;
 double max = mf.max;
     double num=0, denom=0;
     int i;
     for(i=0; i<mf.length; i++) {
      num += mf.degree[i] * mf.conc[i].center();
      denom += mf.degree[i];
     }
     if(denom==0) return (min+max)/2;
     return num/denom;

}


/*======================================================*/
/*  TypeLV TP_T_error                                   */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the family fam                        */
/*------------------------------------------------------*/

static double TP_T_error_fam_equal(double x, int i){
   double list[5] = {-500.0,-20.0,0.0,20.0,500.0};
   return FMF_xfl_sh_triangular_equal(x,i,-2500.0,2500.0,19.607843137254903,list,5);
}

/*------------------------------------------------------*/
/* Description of the label ENG                         */
/*------------------------------------------------------*/

static double TP_T_error_ENG_equal(double x){
   return TP_T_error_fam_equal(x,0);}

/*------------------------------------------------------*/
/* Description of the label ENP                         */
/*------------------------------------------------------*/

static double TP_T_error_ENP_equal(double x){
   return TP_T_error_fam_equal(x,1);}

/*------------------------------------------------------*/
/* Description of the label EZ                          */
/*------------------------------------------------------*/

static double TP_T_error_EZ_equal(double x){
   return TP_T_error_fam_equal(x,2);}

/*------------------------------------------------------*/
/* Description of the label EPP                         */
/*------------------------------------------------------*/

static double TP_T_error_EPP_equal(double x){
   return TP_T_error_fam_equal(x,3);}

/*------------------------------------------------------*/
/* Description of the label EPG                         */
/*------------------------------------------------------*/

static double TP_T_error_EPG_equal(double x){
   return TP_T_error_fam_equal(x,4);}

/*======================================================*/
/*  TypeLV TP_T_Derror                                  */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the family fam                        */
/*------------------------------------------------------*/

static double TP_T_Derror_fam_equal(double x, int i){
   double list[5] = {-1000.0,-100.0,0.0,100.0,1000.0};
   return FMF_xfl_sh_triangular_equal(x,i,-1500.0,1500.0,11.764705882352942,list,5);
}

/*------------------------------------------------------*/
/* Description of the label DNG                         */
/*------------------------------------------------------*/

static double TP_T_Derror_DNG_equal(double x){
   return TP_T_Derror_fam_equal(x,0);}

/*------------------------------------------------------*/
/* Description of the label DNP                         */
/*------------------------------------------------------*/

static double TP_T_Derror_DNP_equal(double x){
   return TP_T_Derror_fam_equal(x,1);}

/*------------------------------------------------------*/
/* Description of the label DZ                          */
/*------------------------------------------------------*/

static double TP_T_Derror_DZ_equal(double x){
   return TP_T_Derror_fam_equal(x,2);}

/*------------------------------------------------------*/
/* Description of the label DPP                         */
/*------------------------------------------------------*/

static double TP_T_Derror_DPP_equal(double x){
   return TP_T_Derror_fam_equal(x,3);}

/*------------------------------------------------------*/
/* Description of the label DPG                         */
/*------------------------------------------------------*/

static double TP_T_Derror_DPG_equal(double x){
   return TP_T_Derror_fam_equal(x,4);}

/*======================================================*/
/*  TypeLV TP_T_pwm                                     */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the label RR                          */
/*------------------------------------------------------*/

static double TP_T_pwm_RR_equal(double x){
   return MF_xfl_singleton_equal(x,-100.0,100.0,0.7843137254901961,-95.0);
}

static double TP_T_pwm_RR_center(){
   return -95.0;
}

/*------------------------------------------------------*/
/* Description of the label RM                          */
/*------------------------------------------------------*/

static double TP_T_pwm_RM_equal(double x){
   return MF_xfl_singleton_equal(x,-100.0,100.0,0.7843137254901961,-40.0);
}

static double TP_T_pwm_RM_center(){
   return -40.0;
}

/*------------------------------------------------------*/
/* Description of the label RL                          */
/*------------------------------------------------------*/

static double TP_T_pwm_RL_equal(double x){
   return MF_xfl_singleton_equal(x,-100.0,100.0,0.7843137254901961,-4.0);
}

static double TP_T_pwm_RL_center(){
   return -4.0;
}

/*------------------------------------------------------*/
/* Description of the label STOP                        */
/*------------------------------------------------------*/

static double TP_T_pwm_STOP_equal(double x){
   return MF_xfl_singleton_equal(x,-100.0,100.0,0.7843137254901961,0.0);
}

static double TP_T_pwm_STOP_center(){
   return 0.0;
}

/*------------------------------------------------------*/
/* Description of the label DL                          */
/*------------------------------------------------------*/

static double TP_T_pwm_DL_equal(double x){
   return MF_xfl_singleton_equal(x,-100.0,100.0,0.7843137254901961,4.0);
}

static double TP_T_pwm_DL_center(){
   return 4.0;
}

/*------------------------------------------------------*/
/* Description of the label DM                          */
/*------------------------------------------------------*/

static double TP_T_pwm_DM_equal(double x){
   return MF_xfl_singleton_equal(x,-100.0,100.0,0.7843137254901961,40.0);
}

static double TP_T_pwm_DM_center(){
   return 40.0;
}

/*------------------------------------------------------*/
/* Description of the label DR                          */
/*------------------------------------------------------*/

static double TP_T_pwm_DR_equal(double x){
   return MF_xfl_singleton_equal(x,-100.0,100.0,0.7843137254901961,95.0);
}

static double TP_T_pwm_DR_center(){
   return 95.0;
}

/*======================================================*/
/*  Rulebase RL_reglas                                  */
/*======================================================*/

static void RL_reglas(double Error, double Derror, double *pwm) {
 double _rl;

 double _pwm_degree[25];
 Consequent _pwm_conc[25];
 FuzzyNumber _pwm;
 _pwm.min = -100.0;
 _pwm.max = 100.0;
 _pwm.step = 0.7843137254901961;
 _pwm.length = 25;
 _pwm.degree = _pwm_degree;
 _pwm.conc = _pwm_conc;
 int _pwm_i = 0;

 double _Error_eq[5];
 _Error_eq[0] = TP_T_error_ENG_equal(Error);
 _Error_eq[1] = TP_T_error_ENP_equal(Error);
 _Error_eq[2] = TP_T_error_EZ_equal(Error);
 _Error_eq[3] = TP_T_error_EPP_equal(Error);
 _Error_eq[4] = TP_T_error_EPG_equal(Error);

 double _Derror_eq[5];
 _Derror_eq[0] = TP_T_Derror_DNG_equal(Derror);
 _Derror_eq[1] = TP_T_Derror_DNP_equal(Derror);
 _Derror_eq[2] = TP_T_Derror_DZ_equal(Derror);
 _Derror_eq[3] = TP_T_Derror_DPP_equal(Derror);
 _Derror_eq[4] = TP_T_Derror_DPG_equal(Derror);

 _rl = OP_operadores_And(_Error_eq[0],_Derror_eq[0]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RR_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RR_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[0],_Derror_eq[1]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RR_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RR_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[0],_Derror_eq[2]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RM_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RM_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[0],_Derror_eq[3]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RM_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RM_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[0],_Derror_eq[4]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_STOP_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_STOP_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[1],_Derror_eq[0]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RR_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RR_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[1],_Derror_eq[1]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RM_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RM_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[1],_Derror_eq[2]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RL_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RL_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[1],_Derror_eq[3]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_STOP_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_STOP_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[1],_Derror_eq[4]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DL_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DL_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[2],_Derror_eq[0]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RM_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RM_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[2],_Derror_eq[1]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RL_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RL_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[2],_Derror_eq[2]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_STOP_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_STOP_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[2],_Derror_eq[3]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DL_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DL_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[2],_Derror_eq[4]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DM_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DM_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[3],_Derror_eq[0]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_RL_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_RL_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[3],_Derror_eq[1]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_STOP_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_STOP_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[3],_Derror_eq[2]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DL_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DL_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[3],_Derror_eq[3]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DM_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DM_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[3],_Derror_eq[4]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DR_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DR_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[4],_Derror_eq[0]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_STOP_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_STOP_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[4],_Derror_eq[1]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DL_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DL_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[4],_Derror_eq[2]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DM_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DM_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[4],_Derror_eq[3]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DR_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DR_center;
 _pwm_i++;

 _rl = OP_operadores_And(_Error_eq[4],_Derror_eq[4]);
 _pwm_degree[_pwm_i] = _rl;
 _pwm_conc[_pwm_i].equal = TP_T_pwm_DR_equal;
 _pwm_conc[_pwm_i].center = TP_T_pwm_DR_center;
 _pwm_i++;

 *pwm = OP_operadores_Defuz(_pwm);
}


/*======================================================*/
/*                   Inference Engine                   */
/*======================================================*/

void fuzzyControlInferenceEngine(double Ecenit, double D_Ecenit, double Eazimut, double D_Eazimut, double *_d_PWM_cenit, double *_d_PWM_azimut) {
 double PWM_cenit;
 double PWM_azimut;
 RL_reglas(Ecenit, D_Ecenit, &PWM_cenit);
 RL_reglas(Eazimut, D_Eazimut, &PWM_azimut);
 *_d_PWM_cenit = PWM_cenit;
 *_d_PWM_azimut = PWM_azimut;
}

